spring:
  application:
    name: quotes

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

###
#   Database Settings
###
  datasource:
      #<------H2-------------->
      platform: h2
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:quotes_db
      initialization-mode: always
      #<----------End H2----------->

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true


  ##############################################
#   H2
###
  h2:
    console:
      enabled: true
      path: /h2

##############################################

server:
  #servlet:
  #  context-path: /quotes
  port: 8081
