spring:
  application:
    name: quotes

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


###
#   Database Settings
###
  datasource:
      #<------H2-------------->
      platform: h2
      driverClassName: org.h2.Driver
      url: jdbc:h2:./data/quotes_db;DB_CLOSE_ON_EXIT=FALSE; #AUTO_SERVER=TRUE
      #url: jdbc:h2:mem:quotes_db; DB_CLOSE_DELAY=-1
      #username: sa
      #password:
      initialization-mode: always
      #<----------End H2----------->


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
      #properties.hibernate.temp.use_jdbc_metadata_defaults: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true


  ##############################################
#   H2
###
  h2:
    console:
      enabled: true
      path: /h2

##############################################

server:
  #servlet:
  #  context-path: /quotes
  port: 8081
  #port: 8099
