drop table if exists quotes CASCADE;
drop table if exists users CASCADE;

create table quotes (
    id bigint generated by default as identity primary key,
    dislike bigint,
    like_q bigint,
    text varchar(255),
    timestamp timestamp default now(),
    topic varchar(255),
    user_id bigint
    );
create table users (
    id bigint generated by default as identity primary key,
     email varchar(255),
     firstname varchar(255),
     lastname varchar(255)
     );
alter table quotes add constraint fk_ref_quotes_id foreign key (user_id) references users;


--Users
INSERT INTO users (firstname, lastname, email) VALUES
('firstname1', 'lastname1', 'email1'),
('firstname2', 'lastname2', 'email2'),
('firstname3', 'lastname3', 'email3'),
('firstname4', 'lastname4', 'email4');

--Quotes
INSERT INTO quotes (text, topic, like_q, dislike, timestamp, user_id) VALUES
('text1', 'SOCIETY', 120, 4, '2019-06-15', 1),
('text2', 'SOCIETY', 12, 3, '2019-06-10', 1),
('text3', 'SOCIETY', 10, 2, '2019-07-26', 1),
('text4', 'SOCIETY', 12, 0, '2019-06-2', 2),
('text5', 'SOCIETY', 12, 10, '2019-06-17', 2),
('text6', 'SOCIETY', 24, 100, '2019-06-15', 3),
('text7', 'SOCIETY', 124, 16, '2019-06-26', 4),


('text8', 'CULTURE', 12, 4, '2019-07-22', 1),
('text9', 'CULTURE', 26, 4, '2019-07-23', 1),
('text10', 'CULTURE', 130, 4, '2019-07-24', 2),
('text11', 'CULTURE', 1, 4, '2019-08-27', 2),
('text12', 'CULTURE', 129, 34, '2019-06-1', 2),
('text13', 'CULTURE', 17, 41, '2019-08-3', 2),
('text14', 'CULTURE', 22, 4, '2019-07-5', 3),
('text15', 'CULTURE', 1276, 18, '2019-06-2', 4),
('text16', 'CULTURE', 128, 45, '2019-06-12', 4);
