drop table if exists quotes CASCADE;
drop table if exists users CASCADE;

create table quotes (
    id bigint generated by default as identity primary key,
    dislike bigint,
    like_q bigint,
    text varchar(255),
    timestamp varchar(255),
    --timestamp timestamp,
    topic varchar(255),
    user_id bigint
    );
create table users (
    id bigint generated by default as identity primary key,
     email varchar(255),
     firstname varchar(255),
     lastname varchar(255)
     );
alter table quotes add constraint fk_ref_quotes_id foreign key (user_id) references users;


--Users
INSERT INTO users (firstname, lastname, email) VALUES
('firstname1', 'lastname1', 'email1'),
('firstname2', 'lastname2', 'email2'),
('firstname3', 'lastname3', 'email3'),
('firstname4', 'lastname4', 'email4');

--Quotes
INSERT INTO quotes (text, topic, like_q, dislike, timestamp, user_id) VALUES
('text1', 'SOCIETY', 120, 4, '', 1),
('text2', 'SOCIETY', 12, 3, '', 1),
('text3', 'SOCIETY', 10, 2, '', 1),
('text4', 'SOCIETY', 12, 0, '', 2),
('text5', 'SOCIETY', 12, 10, '', 2),
('text6', 'SOCIETY', 24, 100, '', 3),
('text7', 'SOCIETY', 124, 16, '', 4),


('text8', 'CULTURE', 12, 4, '', 1),
('text9', 'CULTURE', 26, 4, '', 1),
('text10', 'CULTURE', 130, 4, '', 2),
('text11', 'CULTURE', 1, 4, '', 2),
('text12', 'CULTURE', 129, 34, '', 2),
('text13', 'CULTURE', 17, 41, '', 2),
('text14', 'CULTURE', 22, 4, '', 3),
('text15', 'CULTURE', 1276, 18, '', 4),
('text16', 'CULTURE', 128, 45, '', 4);
